name:       switcherio
version:    '0.1.0.0'
github:     AHW214/switcher.io
license:    MIT
author:     Adam Weider
maintainer: adamweider98@gmail.com
copyright:  Adam Weider

extra-source-files:
- README.md

synopsis: Randomly switch the names of your files
category: Silly Tool

description: Please see the README on GitHub at <https://github.com/AHW214/switcher.io#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- directory
- filepath
- random
- safe-exceptions

library:
  source-dirs: src

executables:
  switch:
    main:        Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - switcherio
